apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-maven-app
  labels:
    app: jma
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: jma
    spec:
      containers:
      - name: hello-world
        image: ghcr.io/cr0nems/simple-java-maven-app-java:latest
        ports:
        - containerPort: 80
