name: Angular Check, Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - feature-*
    paths:
      - "angular/**"

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKE_ANGULAR }}
        with:
          projectBaseDir: ./angular/
  
  Build:
    name: Setup Node.js and build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: angular
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:headless

      - name: Build
        run: npm run build


      - name: Push to GHCR
        uses: macbre/push-to-ghcr@v13
        with:
          dockerfile: ./angular/Dockerfile
          context: ./angular
          github_token: ${{ secrets.TOKEN }}
          image_name: ${{ github.repository }}-angular
